SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sp_goods.views import IndexView

urlpatterns = [
    # 127.0.0.1:8000
    url(r'^$', IndexView.as_view(), name="商城首页"),
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 绑定 用户模块子路由
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),
    # 绑定 商品模块子路由
    url(r'^goods/', include("sp_goods.urls", namespace="sp_goods")),
    # 购物车模块
    url(r'^car/', include('sp_car.urls', namespace='sp_car')),
    # 订单模块
    url(r'^order/', include('sp_order.urls', namespace="sp_order")),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url

from sp_user.views import (RegisterView,
                           LoginView,
                           CenterView,
                           AddressView,
                           InfoView,
                           LogoutView,
                           info,
                           SendCodeView,
                           upload_head,
                           AddressAddView)

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登录
    url(r'^center/$', CenterView.as_view(), name="center"),  # 个人中心
    url(r'^address/$', AddressView.as_view(), name="address"),  # 收货地址
url(r'^address/add/$', AddressAddView.as_view(), name="address_add"),  # 添加收货地址
    url(r'^info/$', InfoView.as_view(), name="info"),  # 个人资料
    # url(r'^info/$', info, name="info"),  # 个人资料
    url(r'^logout/$', LogoutView.as_view(), name="logout"),  # 退出
    url(r'^SendCodeView/$', SendCodeView.as_view(), name="SendCodeView"),  # 发送验证码
    url(r'^upload_head/$', upload_head, name="upload_head"),  # 上传头像
]

SpMarket/apps/sp_user/models.py
from django.core import validators
from django.db import models

# Create your models here.
from db.base_model import BaseModel


class Users(BaseModel):
    # 更新时间,修改时间,是否删除从BaseModel继承
    """
    用户模型
    """
    # 性别选项
    sex_choices = (
        (1, '男'),
        (2, "女"),
        (3, "保密"),
    )
    nickname = models.CharField(verbose_name='昵称',
                                max_length=20,
                                null=True,
                                blank=True,
                                )
    phone = models.CharField(verbose_name='手机号码',
                             max_length=11,
                             validators=[
                                 validators.RegexValidator(r'^1[3-9]\d{9}$',"手机号码格式错误")
                             ],
                             )
    password = models.CharField(verbose_name='密码',
                                max_length=64,
                                # validators=[
                                #     validators.MinLengthValidator(6),
                                #     validators.MaxLengthValidator(16),
                                # ]
                                )
    gender = models.SmallIntegerField(verbose_name='性别',
                                      default=3,
                                      choices=sex_choices,
                                      )
    head = models.ImageField(verbose_name='用户头像',
                             upload_to='head/%Y/%m',
                             default='user/201809/25/1.jpg',
                             )
    birthday = models.DateField(verbose_name='出生日期',
                                null=True,
                                blank=True,
                                )
    school_name = models.CharField(verbose_name='学校名称',
                                   max_length=50,
                                   null=True,
                                   blank=True,
                                   )
    address = models.CharField(verbose_name='学校详细地址',
                               max_length=100,
                               null=True,
                               blank=True,
                               )
    hometown = models.CharField(verbose_name='老家',
                                max_length=100,
                                null=True, blank=True,
                                )

    class Meta:
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.phone


class TestImageModel(models.Model):
    head = models.ImageField(upload_to="user/%Y%m/%d",
                             verbose_name="用户头像")




class UserAddress(BaseModel):
    """用户收货地址管理"""
    user = models.ForeignKey(to="Users", verbose_name="创建人")
    username = models.CharField(verbose_name="收货人", max_length=100)
    phone = models.CharField(verbose_name="收货人电话",
                             max_length=11,
                             validators=[
                                 validators.RegexValidator(r'^1[3-9]\d{9}$', "手机号码格式错误!")
                             ],
                             )
    hcity = models.CharField(verbose_name="省", max_length=100)
    hproper = models.CharField(verbose_name="市", max_length=100, blank=True, default='')
    harea = models.CharField(verbose_name="区", max_length=100, blank=True, default='')
    brief = models.CharField(verbose_name="详细地址", max_length=255)
    isDefault = models.BooleanField(verbose_name="是否设置为默认", default=False, blank=True)

    class Meta:
        verbose_name = "收货地址管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

SpMarket/apps/sp_user/forms.py
from django import forms
from django.core import validators

from sp_user.helper import set_password
from sp_user.models import Users, UserAddress


class RegisterForm(forms.ModelForm):
    # form,前台一个表单,后台一个form类,

    # 确认密码
    repassword = forms.CharField(max_length=16,
                                 min_length=6,
                                 error_messages={
                                     "required": "请确认密码",

                                 },
                                 widget=forms.PasswordInput(attrs={
                                     "class": "login-password",
                                     "placeholder": "请确认密码",
                                 }))

    verify_code = forms.CharField(
        required=True,
        error_messages={
            "required": "请输入验证码"
        },
        widget=forms.TextInput(attrs={"class": "reg-yzm", "placeholder": "输入验证码"})
    )

    agree = forms.BooleanField(
        required=True,
        error_messages={
            "required": "必须同意用户协议"
        }
    )

    class Meta:
        model = Users
        fields = ['phone', 'password']

        widgets = {
            "phone": forms.TextInput(attrs={
                "class": "login-name",
                "placeholder": "请输入手机号码"
            }),
            "password": forms.TextInput(attrs={
                "class": "login-password",
                "placeholder": "请输入密码",
                "type": "password"
            }),
        }

        # 自定义错误信息
        error_messages = {
            "phone": {
                "required": "请输入手机号码"
            },
            "password": {
                "required": "请输入密码",
                "min_length": "密码必须大于6",
                "max_length": "密码必须小于16",
            },
        }

    def __init__(self, *args, **kwargs):
        # 调用父类方法
        super().__init__(*args, **kwargs)
        # 自定义验证 密码长度验证 6-16
        self.fields['password'].validators.append(validators.MinLengthValidator(6))
        self.fields['password'].validators.append(validators.MaxLengthValidator(16))

    # 自定义方法验证
    def clean_phone(self):
        # 验证手机号码是否被注册
        phone = self.cleaned_data.get("phone")  # 传入的手机号码
        # 数据库查询工作
        rs = Users.objects.filter(phone=phone).exists()
        if rs:
            # 抛出异常
            raise forms.ValidationError("该手机号码已经注册")
        # 返回清洗后的值
        return phone

    # 验证短信验证码
    def clean_verify_code(self):
        # self.cleaned_data.get('verify_code')
        # 获取用户提交的验证码
        verify_code = self.cleaned_data.get('verify_code')
        # 获取原始数据保存的验证码
        session_code = self.data.get("verify_code")
        if verify_code != session_code:
            raise forms.ValidationError("验证码错误")
        return verify_code

    # 综合验证
    def clean(self):
        # 所有清洗后的数据
        cleaned_data = super().clean()
        pwd1 = cleaned_data.get("password")
        pwd2 = cleaned_data.get("repassword")
        # 比较两次密码是否一致
        if pwd1 and pwd2 and pwd1 != pwd2:
            raise forms.ValidationError({"repassword": "密码不一致"})
        else:
            if pwd1:
                # 对密码加密
                cleaned_data['password'] = set_password(pwd1)
        # 返回所有清洗后的数据
        return cleaned_data


class LoginForm(forms.ModelForm):
    # 登录 form
    class Meta:
        model = Users
        fields = ['phone', 'password']
        widgets = {
            'phone': forms.TextInput(attrs={"class": "login-name", "placeholder": "请输入号码"}),
            'password': forms.PasswordInput(
                attrs={"class": "login-password", "placeholder": "请输入密码"})
        }

        error_messages = {
            "phone": {
                "required": "请输入手机号",
            },
            "password": {
                "required": "请输入密码",
            }
        }

    def clean(self):
        cleaned_data = super().clean()
        # 验证手机号码和密码是否正确
        phone = cleaned_data.get('phone')
        password = cleaned_data.get('password', "")
        # 通过手机查询数据,如果有就验证密码,没有则报错
        user = Users.objects.filter(phone=phone).first()
        if user is None:
            raise forms.ValidationError({"phone": "该号码没有注册"})
        else:
            # 存在手机号码
            password_in_db = user.password
            password = set_password(password)
            if password_in_db != password:
                raise forms.ValidationError({"password": "密码错误!"})
            else:
                # 保存用户的信息对象user,到cleaned-data
                cleaned_data['user'] = user
                return cleaned_data


class AddressAddForm(forms.ModelForm):
    """用户添加收货地址的表单"""

    class Meta:
        model = UserAddress
        exclude = ['create_time', 'update_time', 'is_delete', 'user']

        error_messages = {
            'username': {
                'required': "请填写用户名！",
            },
            'phone': {
                'required': "请填写手机号码！",
            },
            'brief': {
                'required': "请填写详细地址！",
            },
            'hcity': {
                'required': "请填写完整地址！",
            },
            'hproper': {
                'required': "请填写完整地址！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    # 判断一个人最多六个收货地址

SpMarket/apps/sp_user/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from db.base_view import BaseVerifyView
from sp_user.forms import RegisterForm, LoginForm, AddressAddForm
from sp_user.helper import verify_login_required
from sp_user.models import Users, UserAddress


class RegisterView(View):
    # 注册功能
    def get(self, request):
        # 使用form渲染页面
        form = RegisterForm()
        return render(request, "sp_user/reg.html", {"form": form})

    def post(self, request):
        # 1.接收数据
        session_code = request.session.get("random_code")
        # 强制转换成真正的字典
        data = request.POST.dict()
        data["session_code"] = session_code
        # 2.处理数据
        form = RegisterForm(data)
        # 3.响应
        if form.is_valid():
            form.save()
            # 注册成功,跳转到登录页面
            return redirect(reverse("sp_user:login"))
        # 注册失败,回到注册页面,提示错误信息
        return render(request, "sp_user/reg.html", {
            "form": form
        })


class LoginView(View):
    # 登录功能
    def get(self, request):
        login_form = LoginForm()
        return render(request, "sp_user/login.html", {"form": login_form})

    def post(self, request):
        # 1.接收数据
        # 2.处理数据
        login_form = LoginForm(request.POST)
        # 3.响应
        if login_form.is_valid():
            # 验证成功,保存登录标识到session
            user = login_form.cleaned_data.get('user')
            request.session["ID"] = user.pk
            request.session["phone"] = user.phone
            # 设置有效期,关闭浏览则结束
            request.session.set_expiry(0)

            # 跳转到用户中心
            # 获取到跳转的位置
            if request.GET.get('next', None):
                return redirect(request.GET.get('next'))
            return redirect(reverse('sp_user:center'))
        # 验证失败
        return render(request, "sp_user/login.html", {"form": login_form})


class CenterView(BaseVerifyView):
    # 个人中心功能
    def get(self, request):
        phone = request.session.get('phone')
        context = {
            'phone': phone,
            "footer": 5
        }
        return render(request, "sp_user/member.html", context)

    def post(self, request):
        pass


class AddressView(BaseVerifyView):
    # 收货地址功能
    def get(self, request):
        pass

    def post(self, request):
        pass


class InfoView(BaseVerifyView):
    # 个人资料功能

    def get(self, request):
        # 验证用户是否登录
        # 判断session中是否有用户id
        user_id = request.session.get('ID')
        # 查询当前用户信息
        user = Users.objects.filter(pk=user_id).first()
        context = {
            "user": user
        }
        return render(request, "sp_user/infor.html", context)

    def post(self, request):
        # 1接收数据
        user_id = request.session.get('ID')
        data = request.POST
        file = request.FILES['head']
        # 2处理数据
        # 更新用户头像
        user = Users.objects.get(pk=user_id)
        user.head = file
        user.save()
        # 3响应
        return redirect(reverse("sp_user:center"))


# 单独使用一个视图函数处理图片上传
@csrf_exempt #移除令牌限制
def upload_head(request):
    if request.method == "POST":
        # 获取用户id
        user_id = request.session.get('ID')
        # 获取用户对象
        user = Users.objects.get(pk=user_id)
        # 保存图片
        user.head = request.FILES['file']  # 通过键获取文件
        user.save()
        return JsonResponse({"error": 0})
    else:
        return JsonResponse({"error": 1})


# 函数形式登录验证装饰器
@verify_login_required
def info(request):
    return render(request, "sp_user/infor.html")


class LogoutView(View):
    # 退出功能
    def get(self, request):
        pass

    def post(self, request):
        pass


class SendCodeView(View):
    """
    发送短信验证码
    """

    def post(self, request):
        # 1.接收数据
        phone = request.POST.get("tel", "")
        # 2.处理数据
        # 手机号码格式判断
        import re
        # 设置验证的正则规则
        phone_re = re.compile("^1[3-9]\d{9}$")
        # 匹配手机号码
        res = re.search(phone_re, phone)
        if res is None:
            # 手机号码格式错误
            return JsonResponse({"status": "400", "msg": "手机号码格式错误"})

        # 号码是否已注册
        res = Users.objects.filter(phone=phone).exists()
        if res:
            return JsonResponse({"status": "400", "msg": "手机号码已注册"})

        # 生成随机验证码
        import random
        random_code = "".join([str(random.randint(0, 9)) for _ in range(4)])
        # print(random_code)

        # 发送验证码 阿里云  开发阶段模拟
        print("===code========={}=====".format(random_code))

        # 将生成的随机码保存到session中
        request.session['random_code'] = random_code
        request.session.set_expiry(60)

        # 3.响应 json,告知是否发送成功
        return JsonResponse({"status": "200"})



# address/
class AddressView(BaseVerifyView):
    """
        展示用户收货地址
    """

    def get(self, request):
        # 当前登录用户的id
        user_id = request.session.get("ID")
        # 从数据库中查询 当前用户的所有的未删除的收货地址
        address_list = UserAddress.objects.filter(user_id=user_id, is_delete=False).order_by("-isDefault")

        # 渲染数据到页面
        context = {
            "address_list": address_list,
        }
        return render(request, "sp_user/address.html", context)

    def post(self, request):
        """
            设置默认的收货地址
        """
        # 1. 接收参数 收货地址的主键pk addr_id
        user_id = request.session.get("ID")
        addr_id = request.POST.get("addr_id", 0)
        # 2. 处理参数
        # 将其他的设置为false
        UserAddress.objects.filter(user_id=user_id).update(isDefault=False)
        # 将该用户的 对应的收货地址的id设置为默认
        rows = UserAddress.objects.filter(user_id=user_id, pk=addr_id).update(isDefault=True)
        if rows == 0:
            return JsonResponse({"error": 1, "msg": "设置失败!"})
            # 3. 响应
        return JsonResponse({"error": 0})


# address/add/
class AddressAddView(BaseVerifyView):
    """
        收货地址添加
    """

    def get(self, request):
        return render(request, "sp_user/address_add.html")

    def post(self, request):
        # 1. 接收参数
        # 单独获取当前登录用户的 记录
        user_id = request.session.get("ID")
        data = request.POST
        # 2. 处理参数
        form = AddressAddForm(data)
        if form.is_valid():
            form.instance.user_id = user_id

            # 判断当前用户的收货地址的数量
            count = UserAddress.objects.filter(user_id=user_id, is_delete=False).count()
            if count == 6:
                return JsonResponse({"error": 1, "errors": {"phone": ["收货地址只能添加6个!"]}})

            # 默认的收货地址只能有一个, 如果当前添加的收货地址为True,当前用户其它收货地址都为False
            if form.cleaned_data.get("isDefault"):
                UserAddress.objects.filter(user_id=user_id).update(isDefault=False)

            form.save()
            return JsonResponse({"error": 0})
        else:
            # 3. 响应
            # form.errors['phone'][0]
            return JsonResponse({"error": 1, "errors": form.errors})

SpMarket/templates/sp_user/address.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">管理收货地址</a>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url 'sp_user:address_add' %}" class="">
                <i class="am-icon-plus"></i>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="address-list">
    {% for address in address_list %}
    <li  {% if address.isDefault %}class="curr"{% endif %}>
            <p>收货人：{{ address.username }}&nbsp;&nbsp;{{ address.phone }}</p>
            <p class="order-add1">收货地址：{{ address.hcity }}{{ address.hproper }}{{ address.harea }}&emsp;{{ address.brief }}</p>
            <hr/>
            <div class="address-cz">
                <label class="am-radio am-warning">
                    <input type="radio" name="radio3" value="{{ address.pk }}" data-am-ucheck {% if address.isDefault %}checked{% endif %}> 设为默认
                </label>
                <a href=""><img src="{% static 'images/bj.png' %}" width="18"/>&nbsp;编辑</a>
                <a href="">删除</a>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endblock %}


{% block footer_js %}
<script>

    $(function () {
        //在所有的radio上绑定点击事件
        $(":radio").on("click",function () {
            //1. 准备数据
            var addr_id = $(this).val();
            {#console.debug(addr_id);#}
            //2. 发送请求
            var data = {
                "addr_id":addr_id,
                "csrfmiddlewaretoken":"{{ csrf_token }}"
            };
            var that = this;
            $.post("{% url 'sp_user:address' %}",data,function(data){
                if(data.error == "0"){
                    //成功
                    //将所有li上的curr类去掉
                    $(".address-list").find("li").removeClass("curr");
                    //将当前li上的curr类加上
                    $(that).parents('li').addClass("curr");
                }else {
                    alert(data.msg);
                    location.reload();
                }
            })
        })
    })
</script>
{% endblock %}

SpMarket/templates/sp_user/address_add.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_js %}
    <script src="{% static 'utils_js/common.js' %}"></script>
    <script src="{% static 'utils_js/Popt.js' %}"></script>
    <script src="{% static 'utils_js/cityJson.js' %}"></script>
    <script src="{% static 'utils_js/citySet.js' %}"></script>
{% endblock %}

{% block meta_css %}
    <style type="text/css">
        ._citys {
            width: 100%;
            height: 100%;
            display: inline-block;
            position: relative;
        }

        ._citys span {
            color: #56b4f8;
            height: 15px;
            width: 15px;
            line-height: 15px;
            text-align: center;
            border-radius: 3px;
            position: absolute;
            right: 1em;
            top: 10px;
            border: 1px solid #56b4f8;
            cursor: pointer;
        }

        ._citys0 {
            width: 100%;
            height: 34px;
            display: inline-block;
            border-bottom: 2px solid #56b4f8;
            padding: 0;
            margin: 0;
        }

        ._citys0 li {
            float: left;
            height: 34px;
            line-height: 34px;
            overflow: hidden;
            font-size: 15px;
            color: #888;
            width: 80px;
            text-align: center;
            cursor: pointer;
        }

        .citySel {
            background-color: #56b4f8;
            color: #fff !important;
        }

        ._citys1 {
            width: 100%;
            height: 80%;
            display: inline-block;
            padding: 10px 0;
            overflow: auto;
        }

        ._citys1 a {
            height: 35px;
            display: block;
            color: #666;
            padding-left: 6px;
            margin-top: 3px;
            line-height: 35px;
            cursor: pointer;
            font-size: 13px;
            overflow: hidden;
        }

        ._citys1 a:hover {
            color: #fff;
            background-color: #56b4f8;
        }

        .ui-content {
            border: 1px solid #EDEDED;
        }

        li {
            list-style-type: none;
        }

        #PoPy {
            background-color: white !important;
        }

        .errorinfo{
            color: red;
        }
    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">新增收货地址</a>
        </h1>
    </header>
    <div style="height: 60px;"></div>
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <ul class="address listview">
            <li>
                <span style="width: 15%">地址:</span>
                <span id="city" style="color:#d7d7d7;padding-left:5px;width: 80%"></span>
            </li>
            <p class="errorinfo" name="hcity"></p>
            <li><input type="text" name="brief" class="add-input" placeholder="详细地址"/></li>
            <p class="errorinfo" name="brief"></p>
            <li><input type="text" name="username" class="add-input" placeholder="收货人"/></li>
            <p class="errorinfo" name="username"></p>
            <li><input type="text" name="phone" class="add-input" placeholder="收货人手机号"/></li>
            <p class="errorinfo" name="phone"></p>
        </ul>
        <div class="moren">
            <label class="am-checkbox am-warning">
                <input type="checkbox" name="isDefault" checked="checked" value="1" data-am-ucheck checked>设为默认
            </label>

        </div>
        <input type="button" class="login-btn" value="确认提交">
    </form>
{% endblock %}

{% block footer_js %}
    <script type="text/javascript">
        $("#city").click(function (e) {
            SelCity(this, e);
            console.log(this);
        });

        $(function () {
            //ajax提交
            $(".login-btn").on("click", function () {
                // 初始化的时候将所有的错误信息清空
                $(".errorinfo").text("");
                //1. 准备数据
                //获取整个form的提交数据
                var data = $("form").serialize(); //获取表单数据序列化成合法的数据提交格式
                //2. 提交
                $.post("{% url 'sp_user:address_add' %}",data,function(data){
                    if(data.error == "0"){
                        location.href = "{% url 'sp_user:address' %}"
                    }else {
                        // 要做失败
                        $.each(data.errors,function (i,e) {
                            {#console.debug(i,e)#}
                            // "" + i + ""  "p[name='"  +i+  "']"
                            $("p[name='"+i+"']").text(e[0])
                        })
                    }
                })
            });
        })
    </script>
{% endblock %}

SpMarket/templates/sp_user/member.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <h1 class="am-header-title">
            <a href="" class="">个人中心</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <div class="member">
        <div class="mem-tit">{{ phone }}
            <a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            <div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
        </div>
        <ul class="member-menu">
            <li>
                <a href="records.html">
                    <p class="yellow">0</p>
                    <p class="black">帐户余额 </p>
                </a>
            </li>
            <li>
                <a href="integral.html">
                    <p class="yellow">0</p>
                    <p class="black">积分 </p>
                </a>
            </li>
            <li>
                <a href="yhq.html">
                    <p class="yellow">0</p>
                    <p class="black">优惠劵 </p>
                </a>
            </li>
            <li>
                <a href="collect.html">
                    <p class="yellow">0</p>
                    <p class="black">我的收藏 </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="user-list">
        <div class="u-list-main">
            <img src="{% static 'images/order-pic.png' %}" width="27"/>
            <span>我的购物订单</span>
            <a href="allorder.html">查看全部订单></a>
        </div>
        <ul class="user-nav">
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}">
                <p>待付款</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
                <p>待收货</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
                <p>待评价</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
                <p>退换货</p></a></li>
        </ul>
        <div class="u-list-main">
            <img src="{% static 'images/order-my.png' %}" width="27"/>
            <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url 'sp_user:info' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="{% url 'sp_user:address' %}"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav"
        style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
        <li>
            <div class="am-gallery-item">
                <a href="job.html" class="">
                    <img src="{% static 'images/m_03.png' %}"/>
                    <p>我要兼职</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="recommend.html" class="">
                    <img src="{% static 'images/m_04.png' %}"/>
                    <p>推荐有奖</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="myrecommend.html" class="">
                    <img src="{% static 'images/m_05.png' %}"/>
                    <p>我的推荐</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_06.png' %}"/>
                    <p>我的佣金</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/m_02.png' %}"/>
                    <p>我的红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="message.html" class="">
                    <img src="{% static 'images/m_07.png' %}"/>
                    <p>我的动态</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/m_08.png' %}"/>
                    <p>客服中心</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_09.png' %}"/>
                    <p>安全退出</p>
                </a>
            </div>
        </li>
    </ul>
    </div>
    <!--客服中心-->
    <div class="qd-box">
        <div class="popup-title">
            <span>客服中心</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
                <img src="{% static 'images/contactqq.png' %}" width="50"/>
                <p class="contactqq">联系QQ</p>
            </a>
            <a href="tel:0791-12345678">
                <img src="{% static 'images/contacttele.png' %}" width="50"/>
                <p class="contacttele">呼叫电话</p>
            </a>
        </div>
    </div>
{% endblock %}

{% block footer %}
 {% include 'public/footer.html' %}
{% endblock %}


{% block footer_js %}
    <script type='text/javascript'>
        (function () {
            new PopUp_api({el: '.index-qd', html: '.qd-box'});
        })()
    </script>
{% endblock %}