SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sp_goods.views import IndexView

urlpatterns = [
    # 127.0.0.1:8000
    url(r'^$', IndexView.as_view(), name="商城首页"),
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 绑定 用户模块子路由
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),
    # 绑定 商品模块子路由
    url(r'^goods/', include("sp_goods.urls", namespace="sp_goods")),
    # 购物车模块
    url(r'^car/', include('sp_car.urls', namespace='sp_car')),
    # 订单模块
    url(r'^order/', include('sp_order.urls', namespace="sp_order")),
]

SpMarket/apps/sp_car/urls.py
from django.conf.urls import url

from sp_car.views import AddCarView, DelCarView, CarShowView

urlpatterns = [
    url(r'^addCar/$', AddCarView.as_view(), name="addCar"),  # 添加购物车
    url(r'^del_car/$', DelCarView.as_view(), name="del_car"),  # 减购物车
    url(r'^$', CarShowView.as_view(), name="购物车首页"),  # 购物车显示
]

SpMarket/apps/sp_goods/urls.py
#!D:\python\python.exe
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from sp_goods.views import IndexView, CategoryView, DetailView

urlpatterns = [
    # 首页路由绑定
    url(r'^$', cache_page(60*60)(IndexView.as_view()), name='IndexView'),  # 首页
    # 商品列表页
    url(r'^category/(?P<cate_id>\d+)_(?P<order>\d)/$',cache_page(60)(CategoryView.as_view()) , name='CategoryView'),  # 列表     (?P<cate_id>\d+)_(?P<order>\d).html
    # 商品详情页
    url(r'^detail/(?P<sku_id>\d+)/$', DetailView.as_view(), name='DetailView'),  # 详情
]

SpMarket/apps/sp_order/urls.py
from django.conf.urls import url
from sp_order.views import EnsureOrderView, OrderView

urlpatterns = [
    url(r'^ensure/$', EnsureOrderView.as_view(), name="确认订单"),
    url(r'^order/$', OrderView.as_view(), name="显示订单"),
]

SpMarket/apps/sp_car/models.py
from django.db import models

# Create your models here.

SpMarket/apps/sp_car/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.http import JsonResponse

from db.base_view import BaseVerifyView
from sp_car.helper import get_car_key
from sp_goods.models import GoodsSKU
from django_redis import get_redis_connection

"""
添加购物车
"""


# addCar
class AddCarView(View):
    def get(self, request):
        pass

    def post(self, request):
        # 1.判断用户是否登录
        user_id = request.session.get("ID")
        if user_id is None:
            return JsonResponse({"error": 1, "msg": "还没有登录哦!"})

        # 2.接收请求参数
        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        # 3. 判断参数合法性
        # 必须为整数
        try:
            sku_id = int(sku_id)
            count = int(count)
        except Exception as e:
            return JsonResponse({"error": 2, "msg": "参数错误!"})
        # 商品必须存在
        try:
            goods_sku = GoodsSKU.objects.get(pk=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({"error": 3, "msg": "商品不存在"})
        # 库存判断
        if goods_sku.stock < count:
            return JsonResponse({"error": 4, "msg": "库存不足!"})

        # 将购物车数据添加到redis中
        # 连接redis
        cnn = get_redis_connection("default")
        # 操作redis
        # 准备key
        car_key = get_car_key(user_id)
        # 添加数据到购物车
        cnn.hincrby(car_key, sku_id, count)
        # 获取购物车中的总的数量
        # 保存到redis中的数据是二进制编码,需要解码才能使用
        car_values = cnn.hvals(car_key)
        total = 0
        for v in car_values:
            # print(v.decode("utf-8"))   # int(v)
            total += int(v)
        # print(car_values)
        return JsonResponse({'error': 0, "msg": "添加成功", "total": total})


"""
减购物车
"""


# del_car
class DelCarView(View):
    def get(self, request):
        pass

    def post(self, request):
        # 1. 判断用户是否登录
        user_id = request.session.get("ID")
        if user_id is None:
            return JsonResponse({"error": 1, "msg": "没有登录,请登录!"})

        # 2. 接收请求参数
        sku_id = request.POST.get("sku_id")
        count = -1

        # 判断参数合法性
        # 1.都要是整数
        try:
            sku_id = int(sku_id)
        except:
            return JsonResponse({"error": 2, "msg": "参数错误!"})

        # 2.商品必须要存在
        try:
            goods_sku = GoodsSKU.objects.get(pk=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({"error": 3, "msg": "商品不存在!"})

        # 从购物车中减去商品数量
        # 链接redis
        cnn = get_redis_connection("default")
        # 操作redis
        # 准备key
        car_key = get_car_key(user_id)
        # 从购物车的数量减
        cnn.hincrby(car_key, sku_id, count)
        # 如果商品sku_id对应的数量为0,就从购物车中删除该商品sku_id
        count = cnn.hget(car_key, sku_id)
        if int(count) < 1:
            cnn.hdel(car_key, sku_id)

        # 获取购物车中的总的商品的数量
        car_values = cnn.hvals(car_key)  # 保存到redis中的数据是 二进制编码了, 需要解码才能使用
        total = 0
        for v in car_values:
            total += int(v)

        return JsonResponse({"error": 0, "msg": "减少成功", "total": total})


# 购物车展示
# car
class CarShowView(BaseVerifyView):
    def get(self, request):
        """
            获取购物车数据
                购物车中的商品数据
                所有商品的总数量和总价格
        """
        user_id = request.session.get('ID')
        # 准备两个变量
        total_price = 0  # 总价格
        total_count = 0  # 总数量

        # 1. 购物车中的总价格和总数量
        # 连接redis
        cnn = get_redis_connection("default")
        # 从redis中获取购物车信息
        # 准备car_key
        car_key = get_car_key(user_id)
        # 取数据
        cars = cnn.hgetall(car_key)  # 字典 ,遍历字典
        # print(cars)
        # 准备一个变量,列表保存多个商品
        goodsList = []
        for sku_id, count in cars.items():
            # print(sku_id,count)
            sku_id = int(sku_id)  # 商品id
            count = int(count)  # 商品数量
            # 获取商品数据
            goods_sku = GoodsSKU.objects.get(pk=sku_id)

            # 需要购物车中商品的数量,在goods_sku对象上添加一个属性
            goods_sku.count = count

            # 将该商品保存到列表中
            goodsList.append(goods_sku)

            # 处理总价格和总数量
            total_count += count
            total_price += goods_sku.price*count

        # 2.所有商品的总价格和总数量

        # 构造列表,渲染数据
        context = {
            "goodsList": goodsList,
            "total_price": total_price,
            "total_count": total_count,
            "footer":3
        }
        return render(request, "sp_car/shopcart.html", context)

    def post(self, request):
        pass

SpMarket/templates/sp_car/shopcart.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">购物车</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <form action="{% url 'sp_order:确认订单' %}" method="get">
    <ul class="shopcart-list">
        {% for goods in goodsList %}
            <li>
                <label class="am-checkbox am-warning">
                    <input type="checkbox" checked="checked" name="sku_ids" value="{{ goods.pk }}" data-am-ucheck checked>
                </label>
                <a href="{% url 'sp_goods:DetailView' goods.pk %}"><img src="{{ MEDIA_URL }}{{ goods.logo }}" class="shop-pic"/></a>
                <div class="shop-list-mid">
                    <div class="tit">
                        <a href="{% url 'sp_goods:DetailView' goods.pk %}">
                            {{ goods.goods_spu.spu_name }}&emsp;{{ goods.sku_name }}
                        </a>
                    </div>
                    <b class="shop-list-price">￥<i>{{ goods.price }}</i> </b>
                </div>
                <div class="list-cart1">
                    <div class="d-stock">
                        <a class="decrease">-</a>
                        <input sku_id="{{ goods.pk }}" id="num" readonly="" class="text_box" name="" type="text" value="{{ goods.count }}">
                        <a class="increase">+</a>
                    </div>
                </div>

            </li>

        {% empty %}
            <!--购物车空的状态-->
            <div class="login-logo">
                <img src="{% static 'images/care.png' %}">
                <p>亲、您的购物车还是空空的哦，快去装满它!</p>
                <a href="{% url 'sp_goods:IndexView' %}" class="goshopping">前去逛逛</a>
            </div>
        {% endfor %}
        <div style="height: 10px; background: #eee;"></div>
    </ul>
    </form>
    <div class="shop-fix">

        <label class="am-checkbox am-warning">
            <input id="check_all" type="checkbox" checked="checked" value="" data-am-ucheck checked>
        </label>
        <a class="del">全选</a>
        <a href="javascript:;" class="js-btn">去结算</a>
        <div class="js-text">
            <P>合计：￥<b id="total_price">{{ total_price }}</b></P>
            <p class="js-car">合计商品数量:<b id="total_count">{{ total_count }}</b></p>
        </div>
    </div>
{% endblock %}

<!--底部-->
{% block footer %}
   {% include 'public/footer.html' %}
{% endblock %}



{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            // 添加
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());


                // 通过ajax请求后台, 添加数据库成功
                var sku_id = self.siblings('input').attr('sku_id');
                var data = {
                    "sku_id": sku_id,
                    "count": 1,
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                };
                $.post("{% url 'sp_car:addCar' %}", data, function (data) {
                    if (data.error == "0") {
                        current_num += 1;
                        if (current_num > 0) {
                            self.siblings(".decrease").fadeIn();
                            self.siblings(".text_box").fadeIn();
                        }
                        self.siblings('input').val(current_num);
                        // 重新计算价格
                        total_price_and_count()
                    } else {
                        alert(data.msg);
                    }
                });
            });

            // 减少
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    //发送ajax请求, 购物车数量减1
                    var sku_id = self.siblings('input').attr('sku_id');
                    var data = {
                        "sku_id": sku_id,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    };
                    $.post("{% url 'sp_car:del_car' %}", data, function (data) {
                        if (data.error == "0") {
                            current_num -= 1;
                            if (current_num < 1) {
                                self.fadeOut();
                                self.siblings(".text_box").fadeOut();
                            }
                            self.siblings('input').val(current_num);
                            // 重新计算价格
                            total_price_and_count()
                        } else {
                            alert(data.msg);
                        }
                    });
                }
            });


            //处理全选功能
            $("#check_all").on("change",function () {
                //获取当前复选框是否被选中
                var status = $(this).prop('checked');
                //将ul里面所有的父选框修改为 status
                $('.shopcart-list').find(":checkbox").prop("checked",status);
                //重新计算价格
                total_price_and_count();
            });

            //处理单独每个商品上的复选框的状态, 绑定一个change事件
            $('.shopcart-list').find(":checkbox").on("change",function () {
                //重新计算价格
                total_price_and_count();
                //如果某一个商品没有被选中,那么全选复选框的选中状态应该为false
                // 当选中的复选框和所有的复选框的数量不一致说明有商品没有被选中
                if($(".shopcart-list").find(":checked").length != $(".shopcart-list").find(":checkbox").length){
                    $("#check_all").prop("checked",false);
                }else {
                    $("#check_all").prop("checked",true);
                }
            });
            //统一的方法, 计算价格和数量
            function total_price_and_count(){
                // 获取所有被选中的复选框
                var checkeds = $(".shopcart-list").find(":checked");
                // 根据checkeds 向上查找li标签
                var lis = checkeds.parents("li");
                // 遍历 lis
                var total_price = 0; //总价格
                var total_count = 0; //总数量
                $.each(lis,function (i,li) {
                    //在该li中 获取价格 和 数量
                    var price = $(li).find(".shop-list-price").find("i").text();
                    var count = $(li).find(".text_box").val();
                    total_price += parseFloat(price)*count;
                    total_count += parseInt(count)
                });
                {#console.debug(total_price,total_count)#}
                // 回显总价格和总数量
                $("#total_price").text(total_price.toFixed(2));
                $("#total_count").text(total_count);
            }


            //结算按钮
            $(".js-btn").on("click",function () {
                if($(".shopcart-list").find(":checked").length > 0){
                    //提交表单
                    $("form").submit();
                }else {
                    alert("请求选择商品!");
                }

            })
        })
    </script>
{% endblock %}