SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sp_goods.views import IndexView

urlpatterns = [
    # 127.0.0.1:8000
    url(r'^$', IndexView.as_view(), name="商城首页"),
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 绑定 用户模块子路由
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),
    # 绑定 商品模块子路由
    url(r'^goods/', include("sp_goods.urls", namespace="sp_goods")),
    # 购物车模块
    url(r'^car/', include('sp_car.urls', namespace='sp_car')),
    # 订单模块
    url(r'^order/', include('sp_order.urls', namespace="sp_order")),
]

SpMarket/apps/sp_car/urls.py
from django.conf.urls import url

from sp_car.views import AddCarView, DelCarView, CarShowView

urlpatterns = [
    url(r'^addCar/$', AddCarView.as_view(), name="addCar"),  # 添加购物车
    url(r'^del_car/$', DelCarView.as_view(), name="del_car"),  # 减购物车
    url(r'^$', CarShowView.as_view(), name="购物车首页"),  # 购物车显示
]

SpMarket/apps/sp_goods/urls.py
#!D:\python\python.exe
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from sp_goods.views import IndexView, CategoryView, DetailView

urlpatterns = [
    # 首页路由绑定
    url(r'^$', cache_page(60*60)(IndexView.as_view()), name='IndexView'),  # 首页
    # 商品列表页
    url(r'^category/(?P<cate_id>\d+)_(?P<order>\d)/$',cache_page(60)(CategoryView.as_view()) , name='CategoryView'),  # 列表     (?P<cate_id>\d+)_(?P<order>\d).html
    # 商品详情页
    url(r'^detail/(?P<sku_id>\d+)/$', DetailView.as_view(), name='DetailView'),  # 详情
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url

from sp_user.views import (RegisterView,
                           LoginView,
                           CenterView,
                           AddressView,
                           InfoView,
                           LogoutView,
                           info,
                           SendCodeView,
                           upload_head,
                           AddressAddView)

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登录
    url(r'^center/$', CenterView.as_view(), name="center"),  # 个人中心
    url(r'^address/$', AddressView.as_view(), name="address"),  # 收货地址
url(r'^address/add/$', AddressAddView.as_view(), name="address_add"),  # 添加收货地址
    url(r'^info/$', InfoView.as_view(), name="info"),  # 个人资料
    # url(r'^info/$', info, name="info"),  # 个人资料
    url(r'^logout/$', LogoutView.as_view(), name="logout"),  # 退出
    url(r'^SendCodeView/$', SendCodeView.as_view(), name="SendCodeView"),  # 发送验证码
    url(r'^upload_head/$', upload_head, name="upload_head"),  # 上传头像
]

SpMarket/apps/sp_goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models

# Create your models here.
from db.base_model import BaseModel

is_on_sale_choices = (
    (0, "下架"),
    (1, "上架"),
)


class Category(BaseModel):
    """
    商品分类
    """
    cate_name = models.CharField(
        verbose_name="分类名称",
        max_length=20
    )
    brief = models.CharField(
        verbose_name="描述",
        max_length=200,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.cate_name

    class Meta:
        verbose_name = "商品分类管理"
        verbose_name_plural = verbose_name


class Unit(BaseModel):
    """
    商品SKU 单位
    """
    name = models.CharField(
        verbose_name="单位",
        max_length=20
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商品单位管理"
        verbose_name_plural = verbose_name


class GoodsSPU(BaseModel):
    """
    商品SPU表
    """
    spu_name = models.CharField(
        verbose_name="商品spu名称",
        max_length=20
    )
    # content = models.TextField(
    #     verbose_name="商品详情"
    # )
    content = RichTextUploadingField(verbose_name="商品详情")

    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = "商品SPU"
        verbose_name_plural = verbose_name


class GoodsSKU(BaseModel):
    """
    商品SKU表
    """
    sku_name = models.CharField(
        verbose_name="商品sku名称",
        max_length=100
    )
    brief = models.CharField(
        verbose_name="商品简介",
        max_length=200,
        null=True,
        blank=True
    )
    price = models.DecimalField(
        verbose_name="商品价格",
        max_digits=9,
        decimal_places=2,
        default=0,
    )
    unit = models.ForeignKey(
        verbose_name="单位",
        to="Unit"
    )
    stock = models.IntegerField(
        verbose_name='库存',
        default=0
    )
    sale_num = models.IntegerField(
        verbose_name='销量',
        default=0
    )
    logo = models.ImageField(
        verbose_name='封面图片',
        upload_to='goods/%Y%m/%d'
    )
    is_on_sale = models.BooleanField(
        verbose_name="是否上架",
        choices=is_on_sale_choices,
        default=0
    )
    category = models.ForeignKey(
        to="Category",
        verbose_name="商品分类"
    )
    goods_spu = models.ForeignKey(
        to="GoodsSPU",
        verbose_name="商品SPU"
    )

    def __str__(self):
        return self.sku_name

    class Meta:
        verbose_name = "商品管理"
        verbose_name_plural = verbose_name


class Gallery(BaseModel):
    """
    商品相册
    """
    img_url = models.ImageField(
        verbose_name="相册图片地址",
        upload_to="goods_gallery/%Y%m/%d"
    )
    goods_sku = models.ForeignKey(
        verbose_name="SKU商品",
        to="GoodsSKU"
    )

    class Meta:
        verbose_name = "商品相册管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "商品: %s的相册" % self.goods_sku.sku_name


class Banner(BaseModel):
    """
    首页轮播
    """
    name = models.CharField(
        verbose_name="轮播活动名",
        max_length=150
    )
    goods_sku = models.ForeignKey(
        verbose_name="SKU商品",
        to="GoodsSKU"
    )
    img_sku = models.ImageField(
        verbose_name="轮播图片地址",
        upload_to="banner/%Y%m/%d"
    )
    order = models.SmallIntegerField(
        verbose_name="排序",
        default=0
    )

    class Meta:
        verbose_name = "首页轮播管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Activity(BaseModel):
    """
        首页活动
    """
    title = models.CharField(verbose_name='活动名称', max_length=150)
    img_url = models.ImageField(verbose_name='活动图片地址',
                                upload_to='activity/%Y%m/%d'
                                )
    url_site = models.CharField(verbose_name='活动的url地址', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动管理"
        verbose_name_plural = verbose_name


class ActivityZone(BaseModel):
    """
        首页活动专区
    """
    title = models.CharField(verbose_name='活动专区名称', max_length=150)
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )
    is_on_sale = models.BooleanField(verbose_name="上否上线",
                                     choices=is_on_sale_choices,
                                     default=0,
                                     )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name


class ActivityZoneGoods(BaseModel):
    """
        首页活动专区商品列表
    """
    activity_zone = models.ForeignKey(to="ActivityZone",
                                      verbose_name="活动专区ID",
                                      )
    goods_sku = models.ForeignKey(to="GoodsSKU",
                                  verbose_name="专区商品SKU_ID",
                                  )

SpMarket/apps/sp_goods/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views import View
from django_redis import get_redis_connection

from sp_goods.models import GoodsSKU, Category


class IndexView(View):
    """首页"""

    def get(self, request):
        # sku 商品
        goods_skus = GoodsSKU.objects.filter(is_delete=False)
        # 组装成字典
        context = {
            "goods_skus": goods_skus,
            "footer":1
        }
        return render(request, 'sp_goods/index.html', context)

    def post(self, request):
        pass


"""
1查询所有商品
2查询所有分类,并显示
3点击某个分类,显示对应分类下的商品
4排序
"""


class CategoryView(View):
    """分类列表页"""
    def get(self, request, cate_id=0, order=1):
        cate_id = int(cate_id)
        # 查询所有分类,并显示
        order = int(order)
        categorys = Category.objects.filter(is_delete=False)
        # sku 全部商品
        # goods_skus = GoodsSKU.objects.filter(is_delete=False)
        # 获取对应分类下的商品
        if cate_id == 0:
            # 默认展示第一个分类
            category = categorys.first()
            # 当cate_id =0时,则等于该分类的pk
            cate_id = category.pk
        else:
            # 获取传入分类id对应的分类
            category = Category.objects.get(pk=cate_id)

        # goods_skus = category.goodssku_set.all().order_by('id')

        # 映射的关系
        order_by_rule = ["id", "-sale_num", "-price", "price", "-create_time"]
        goods_skus = category.goodssku_set.all().order_by(order_by_rule[order])

        # 获取该用户购物车中商品的总数
        user_id = request.session.get('ID', None)
        # 准备变量保存总数量
        total = 0
        if user_id:
            cnn = get_redis_connection('default')
            # 购物车的键
            car_key = "car_%s" % user_id
            car_values = cnn.hvals(car_key)
            for v in car_values:
                total += int(v)

        # 组成字典
        context = {
            "goods_skus": goods_skus,
            "categorys": categorys,
            "cate_id": cate_id,
            "order": order,
            "total": total,
        }

        return render(request, 'sp_goods/category.html', context)

    def post(self, request):
        pass


class DetailView(View):
    """商品详情"""

    def get(self, request, sku_id):
        try:
            # 1.接收数据
            sku_id = int(sku_id)
            # 2.处理数据
            goods_sku = GoodsSKU.objects.get(pk=sku_id)
            # 3.响应
            context = {
                "goods_sku": goods_sku
            }
            return render(request, 'sp_goods/detail.html', context)
        except:
            return redirect(reverse('sp_goods:IndexView'))

    def post(self, request):
        pass

SpMarket/templates/sp_goods/category.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_title %}
    超市
{% endblock %}

{% block meta_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}{% static 'images/order-bot.png' %}
            {% elif order == 3 %}
            {% static 'images/order-top.png' %}
            {% else %}
            {% static 'images/order.png' %}
            {% endif %}) no-repeat right center;
            padding-right: 20px;
            font-style: normal;
        }
    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <form action="/search/" method="get">
            <div class="cate-search">
                <input type="text" name="q" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" value="" class="cate-btn"/>
            </div>
        </form>

    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="list-nav">
        <li {% if order == 0 %} class="current"{% endif %}><a href="{% url 'sp_goods:CategoryView' cate_id 0 %}">综合</a>
        </li>
        <li {% if order == 1 %} class="current"{% endif %}><a href="{% url 'sp_goods:CategoryView' cate_id 1 %}">销量</a>
        </li>
        <li {% if order == 2 or order == 3 %} class="current"{% endif %}>
            <a href="{% url 'sp_goods:CategoryView' cate_id 2 %}" id="price"> <i class="list-price">价格</i></a>
        </li>
        <li {% if order == 4 %} class="current"{% endif %}><a href="{% url 'sp_goods:CategoryView' cate_id 4 %}">新品</a>
        </li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for category in categorys %}
                <li {% if category.pk == cate_id %}
                    class="current"
                {% endif %}><a href="{% url 'sp_goods:CategoryView' category.pk order %}">{{ category.cate_name }}</a>
                </li>
            {% endfor %}


            {#            <li><a href="">进口特产</a></li>#}
            {#            <li class="current"><a href="">休闲零食</a></li>#}

        </div>
        <div class="list-right">

            <ul class="list-pro">
                {% for goods in goods_skus %}
                    <li>
                        <a href="{% url 'sp_goods:DetailView' goods.pk %}"><img src="{{ MEDIA_URL }}{{ goods.logo }}"
                                                                                class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit">
                                <a href="{% url 'sp_goods:DetailView' goods.pk %}">
                                    {{ goods.goods_spu.spu_name }}&emsp;{{ goods.sku_name }}
                                </a>
                            </div>
                            <div class="am-gallery-desc">￥{{ goods.price }}</div>
                            <p>销量：{{ goods.sale_num }}{{ goods.unit.name }}</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input sku_id="{{ goods.pk }}" id="num" readonly="" class="text_box" name="" type="text"
                                       value="0">
                                <a class="increase">+</a>
                            </div>
                        </div>
                        <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                    </li>

                {% empty %}
                    <li style="color: red">该分类下暂无商品哦!</li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'sp_car:购物车首页' %}"><div class="fix-bot-cart"><i id="total_count">{{ total }}</i></div></a>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}

{% block footer_js %}
    {#            {% csrf_token %}#}
    <script>
        //购物数量加减
        // 增加
        $(function () {
            // 添加
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());


                // 完成ajax请求后台,添加数据成功
                var sku_id = self.siblings('input').attr('sku_id');
                var data = {
                    "sku_id": sku_id,
                    "count": 1,
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                };
                $.post("{% url 'sp_car:addCar' %}", data, function (data) {
                    if (data.error == "0") {
                        current_num += 1;
                        if (current_num > 0) {
                            self.siblings(".decrease").fadeIn();
                            self.siblings(".text_box").fadeIn();
                        }
                        self.siblings('input').val(current_num);

                        // 修改购物车总数量
                        $("#total_count").text(data.total)
                    } else if (data.error == "1") {
                        // 没有登录,跳转到登录界面,js代码跳转
                        // 提示,让用户选择是否登录
                        {#var rs = confirm(data.msg)#}
                        {#console.debug(rs)#}
                        if (confirm(data.msg)) {
                            // js代码跳转
                            location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:CategoryView' cate_id order %}"
                        }
                    } else {
                        alert(data.msg);
                    }
                });
            });

            // 减少
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    //发送ajax请求, 购物车数量减1
                    var sku_id = self.siblings('input').attr('sku_id');
                    var data = {
                        "sku_id": sku_id,
                        "csrfmiddlewaretoken": "{{ csrf_token }}"
                    };
                    $.post("{% url 'sp_car:del_car' %}", data, function (data) {
                        if (data.error == "0") {
                            current_num -= 1;
                            if (current_num < 1) {
                                self.fadeOut();
                                self.siblings(".text_box").fadeOut();
                            }
                            self.siblings('input').val(current_num);
                            // 修改购物车总数量
                            $("#total_count").text(data.total)
                        } else if (data.error == "1") {
                            // 没有登录, 跳转到登录页面进行, 通过js代码实现跳转
                            if (confirm(data.msg)) {
                                // js 实现跳转的方法
                                location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:CategoryView' cate_id order %}"
                            }
                        } else {
                            alert(data.msg);
                        }
                    });
                }
            });


            // 改变价格a标签的链接
            if ("{{ order }}" == 2) {
                $("#price").attr('href', "{% url 'sp_goods:CategoryView' cate_id 3 %}")
            } else if ("{{ order }}" == 3) {
                $("#price").attr('href', "{% url 'sp_goods:CategoryView' cate_id 2 %}")
            }
        })

    </script>
{% endblock %}

SpMarket/templates/sp_goods/detail.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_title %}
    超市
{% endblock %}

{% block meta_css %}
    <script>
        function changeImage() {
            document.getElementById("imgflag").src = "{% static 'images/redherat.png' %}";
        }
    </script>

    <style>
        .am-slider-default .am-control-nav {
            text-align: center;
        }

        .am-slider-default .am-control-nav li a.am-active {
            background: #cb2527;
        }

        .am-slider-default .am-control-nav li a {
            border: 0;
            width: 10px;
            height: 10px;
        }
    </style>
{% endblock %}


{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">商品详情</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for gallery in goods_sku.gallery_set.all %}
                <li><img src="{{ MEDIA_URL }}{{ gallery.img_url }}"/></li>
            {% endfor %}
        </ul>
    </div>
    <div class="detal-info" style="position: relative; width: 100%;">
        <p>{{ goods_sku.goods_spu.spu_name }}&emsp;{{ goods_sku.sku_name }}</p>
        <h2>商城价：<span>￥{{ goods_sku.price }}</span></h2>
        <div class="heart">
            <img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()"/>
            <p>收藏</p>
        </div>
    </div>
    <div class="d-amount">
        <h4>数量：</h4>
        <div class="d-stock">
            <a class="decrease">-</a>
            <input sku_id="{{ goods_sku.pk }}" id="num" readonly="" class="text_box" name="" type="text" value="1">
            <input id="id" type="hidden" value="644">
            <a class="increase">+</a>
            <span id="dprice" class="price" style="display:none"> 36</span>
        </div>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <div class="am-tabs detail-list" data-am-tabs>
        <ul class="am-tabs-nav am-nav am-nav-tabs">
            <li class="am-active"><a href="#tab1">商品详情</a></li>
            <li><a href="#tab2">商品评论</a></li>
        </ul>

        <div class="am-tabs-bd">
            <div class="am-tab-panel am-fade am-in am-active detail " id="tab1">
                {{ goods_sku.goods_spu.content|safe }}
            </div>
            <div class="am-tab-panel am-fade detail " id="tab2">
                <!--<div class="comment">
                    <span>好评：</span>
                    <div class="com-good"></div>
                    <span>100%</span>
                </div>
                <div class="comment">
                    <span>中评：</span>
                    <div class="com-bad"></div>
                    <span>0%</span>
                </div>
                <div class="comment">
                    <span>差评：</span>
                    <div class="com-bad"></div>
                    <span>0%</span>
                </div>-->
                <ul class="comment-list">
                    <li class="current"><a href="">全部</a></li>
                    <li><a href="">好评（20）</a></li>
                    <li><a href="">中评（5）</a></li>
                    <li><a href="">差评（0）</a></li>
                </ul>
                <ul class="comment-pic">
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}


{% block footer %}
    <!--底部-->
    <div style=" height: 55px;"></div>
    <ul class="fix-shopping">
        <li><a href="javascript:;" class="join">加入购物车</a></li>
        <li><a href="{% url 'sp_car:购物车首页' %}" class="imm-buy">去结算</a></li>
    </ul>
{% endblock %}


{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                }
            })

            // 加数据到购物车
            $(".join").on("click",function(){
                //发送ajax请求,添加购物车数据
                // 通过ajax请求后台, 添加数据库成功
                var sku_id = $(".text_box").attr('sku_id');
                var count = $(".text_box").val();
                var data = {
                    "sku_id": sku_id,
                    "count": count,
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                };
                {#console.debug(data)#}
                $.post("{% url 'sp_car:addCar' %}", data, function (data) {
                    if (data.error == "0") {
                        //提示
                        alert("添加购物车成功!")
                    } else if (data.error == "1") {
                        // 没有登录, 跳转到登录页面进行, 通过js代码实现跳转
                        if (confirm(data.msg)) {
                            // js 实现跳转的方法
                            location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:DetailView' goods_sku.pk  %}"
                        }
                    } else {
                        alert(data.msg);
                    }
                });
            })

        })
    </script>
{% endblock %}