SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sp_goods.views import IndexView

urlpatterns = [
    # 127.0.0.1:8000
    url(r'^$', IndexView.as_view(), name="商城首页"),
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    # 绑定 用户模块子路由
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),
    # 绑定 商品模块子路由
    url(r'^goods/', include("sp_goods.urls", namespace="sp_goods")),
    # 购物车模块
    url(r'^car/', include('sp_car.urls', namespace='sp_car')),
    # 订单模块
    url(r'^order/', include('sp_order.urls', namespace="sp_order")),
]

SpMarket/apps/sp_order/urls.py
from django.conf.urls import url
from sp_order.views import EnsureOrderView, OrderView

urlpatterns = [
    url(r'^ensure/$', EnsureOrderView.as_view(), name="确认订单"),
    url(r'^order/$', OrderView.as_view(), name="显示订单"),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url

from sp_user.views import (RegisterView,
                           LoginView,
                           CenterView,
                           AddressView,
                           InfoView,
                           LogoutView,
                           info,
                           SendCodeView,
                           upload_head,
                           AddressAddView)

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登录
    url(r'^center/$', CenterView.as_view(), name="center"),  # 个人中心
    url(r'^address/$', AddressView.as_view(), name="address"),  # 收货地址
url(r'^address/add/$', AddressAddView.as_view(), name="address_add"),  # 添加收货地址
    url(r'^info/$', InfoView.as_view(), name="info"),  # 个人资料
    # url(r'^info/$', info, name="info"),  # 个人资料
    url(r'^logout/$', LogoutView.as_view(), name="logout"),  # 退出
    url(r'^SendCodeView/$', SendCodeView.as_view(), name="SendCodeView"),  # 发送验证码
    url(r'^upload_head/$', upload_head, name="upload_head"),  # 上传头像
]

SpMarket/apps/sp_order/models.py
from django.db import models

from db.base_model import BaseModel


class Payment(BaseModel):
    """
        支付方式
    """
    pay_name = models.CharField(verbose_name='支付方式',
                                max_length=20
                                )

    class Meta:
        verbose_name = "支付方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.pay_name


class Transport(BaseModel):
    """
        配送方式
    """
    name = models.CharField(verbose_name='配送方式',
                            max_length=20
                            )
    money = models.DecimalField(verbose_name='金额',
                                max_digits=9,
                                decimal_places=2,
                                default=0
                                )

    class Meta:
        verbose_name = "配送方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class OrderInfo(BaseModel):
    order_status_choices = (
        (0, '待付款'),
        (1, '退发货'),
        (2, '待收货'),
        (3, '待评价'),
        (4, '已完成'),
        (5, '取消订单'),
    )
    """订单信息表"""
    order_sn = models.CharField(verbose_name="订单编号", max_length=150)
    order_money = models.DecimalField(verbose_name="订单总金额", max_digits=9, decimal_places=2, default=0)
    order_goods_money = models.DecimalField(verbose_name="商品总金额", max_digits=9, decimal_places=2, default=0)
    user = models.ForeignKey(to="sp_user.Users", verbose_name="所属用户")
    receiver = models.CharField(verbose_name="收货人姓名", max_length=100)
    receiver_phone = models.CharField(verbose_name="收货人电话", max_length=11)
    address = models.CharField(verbose_name="收货人地址", max_length=200)
    order_status = models.SmallIntegerField(verbose_name="订单状态", choices=order_status_choices, default=0)
    transport = models.ForeignKey(to="Transport", verbose_name="运输方式")
    transport_price = models.DecimalField(verbose_name="运费", max_digits=9, decimal_places=2, default=0)
    payment = models.ForeignKey(to="Payment", verbose_name="支付方式", null=True, blank=True)
    pay_money = models.DecimalField(verbose_name="实际支付金额", max_digits=9, decimal_places=2, default=0)
    description = models.CharField(verbose_name="备注说明", max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = "订单基本信息表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_sn


class OrderGoods(BaseModel):
    """订单商品表"""
    order = models.ForeignKey(to="OrderInfo", verbose_name="所属订单")
    goods_sku = models.ForeignKey(to='sp_goods.GoodsSKU', verbose_name="商品SKU")
    price = models.DecimalField(verbose_name="商品单价", max_digits=9, decimal_places=2, default=0)
    count = models.IntegerField(verbose_name="订单商品数量", default=0)

    class Meta:
        verbose_name = "订单商品"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}-{}".format(self.order.order_sn, self.goods_sku.sku_name)

SpMarket/apps/sp_order/views.py
import os

from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from sp_car.helper import get_car_key
from sp_goods.models import GoodsSKU
from sp_user.helper import verify_login_required
from sp_user.models import UserAddress, Users
from django_redis import get_redis_connection
from sp_order.models import Transport, OrderInfo, OrderGoods
from datetime import datetime
import random
from alipay import AliPay
from django.conf import settings
import time


# ensure/
class EnsureOrderView(View):
    """
        确认订单
    """

    @method_decorator(verify_login_required)
    def get(self, request):  # 显示
        # 接收参数
        user_id = request.session.get("ID")
        """
            1. 需要商品的sku_ids (多个)
            2. 请求方式为GET方式
        """
        # 1. 收货地址的显示
        """
            1. 如果用户没有收货地址,点击添加
            2. 如果有收货地址,并且有默认地址,显示默认地址
                如果没有默认地址,显示最新的一个地址
            3. 点击进去选择其他收货地址
        """
        address = UserAddress.objects.filter(user_id=user_id, is_delete=False, isDefault=True).first()
        if not address:
            # 没有默认的地址
            address = UserAddress.objects.filter(user_id=user_id, is_delete=False).order_by("-create_time").first()

        # 2. 确认商品的显示
        # 链接到redis
        cnn = get_redis_connection("default")
        # 准备 car_key
        car_key = get_car_key(user_id)

        # 接收商品的id 如果传入的字段的值是一个列表, getlist 方法
        sku_ids = request.GET.getlist('sku_ids')

        # 准备一个变量装所有的商品
        goodsList = []
        goods_total_price = 0
        # 获取商品的信息及对应购物车中的数量
        for sku_id in sku_ids:
            # 获取商品的信息
            goods_sku = GoodsSKU.objects.get(pk=sku_id)
            # 获取购物车中的数量
            try:
                count = cnn.hget(car_key, sku_id)
                count = int(count)
            except:
                # 如果购物车中没有获取到商品数量,就跳转到购物车首页
                return redirect(reverse("sp_car:首页"))
            # 提交到goods_sku对象上
            goods_sku.count = count
            # 将商品信息存储到goodsList中
            goodsList.append(goods_sku)
            # 计算商品总价
            goods_total_price += goods_sku.price * count

        # 3. 商品总价和运输方式的选择
        # 运输方式的选择
        transports = Transport.objects.filter(is_delete=False).order_by("money")

        # 合计总价格 商品总价格 + 运费
        transport = transports.first()
        total_price = goods_total_price + transport.money

        context = {
            "address": address,
            "goodsList": goodsList,
            "goods_total_price": goods_total_price,
            "total_price": total_price,
            "transports": transports,
        }
        return render(request, 'sp_order/tureorder.html', context)

    # 使用事务
    @transaction.atomic
    def post(self, request):  # 保存订单数据
        """
            1. 必须登录
            2. 接收请求参数(sku_ids 商品id addr_id 收货地址id transport 运输方式 描述 description)
                判断参数合法性
            3. 将数据保存到订单表

                订单基本信息表(先创建)


                订单商品表(多,后创建)

            4. 清空对应商品在购物车(redis)中的数据
        """

        # 1. 验证是否登录
        user_id = request.session.get("ID")
        if not user_id:
            return JsonResponse({"status": 1, "errmsg": "没有登录!"})
        user = Users.objects.get(pk=user_id)

        # 2. 接收请求参数,判断参数的合法性
        addr_id = request.POST.get('addr_id')
        sku_ids = request.POST.getlist("sku_ids")
        transport = request.POST.get("transport")
        description = request.POST.get("description")

        # 合法性判断
        if not all([addr_id, sku_ids, transport]):
            return JsonResponse({"status": 2, "errmsg": "请求参数错误!"})

        # 判断收货地址是否存在
        try:
            address = UserAddress.objects.get(user_id=user_id,
                                              is_delete=False,
                                              pk=addr_id
                                              )
        except UserAddress.DoesNotExist:
            return JsonResponse({"status": 3, "errmsg": "收货地址不存在"})

        # 判断运输方式是否存在
        try:
            trans = Transport.objects.get(pk=transport, is_delete=False)
        except Transport.DoesNotExist:
            return JsonResponse({"status": 4, "errmsg": "请运输方式!"})

        # 3. 将数据保存到订单中
        # 保存订单基本信息
        # 准备订单编号
        order_sn = "{}{}{}".format(datetime.now().strftime("%Y%m%d%H%M%S"), random.randrange(1000, 9999), user_id)
        # 收货人的地址
        address_info = "{} {} {} {}".format(address.hcity, address.hproper, address.harea, address.brief)

        # 设置事务的保存点
        save_point = transaction.savepoint()

        # 创建订单 判断是否成功
        try:
            orderinfo = OrderInfo.objects.create(order_sn=order_sn,
                                                 user=user,
                                                 receiver=address.username,
                                                 receiver_phone=address.phone,
                                                 address=address_info,
                                                 order_status=0,
                                                 transport=trans,
                                                 transport_price=trans.money,
                                                 description=description)
        except Exception as e:
            print(e)
            return JsonResponse({"status": 5, "errmsg": "创建订单失败!"})

        # 保存订单商品信息
        # 准备一个变量保存商品总金额
        order_goods_money = 0
        # 链接到redis
        cnn = get_redis_connection("default")
        # 准备car_key
        car_key = get_car_key(user_id)
        for sku_id in sku_ids:
            # 判断商品是否存在
            try:
                # 每次都锁定该商品
                goods_sku = GoodsSKU.objects.select_for_update().get(pk=sku_id)
                # goods_sku = GoodsSKU.objects.get(pk=sku_id)
            except GoodsSKU.DoesNotExist:
                # 回滚事务
                transaction.savepoint_rollback(save_point)
                return JsonResponse({"status": 6, "errmsg": "商品不存在!"})

            # 保存订单商品信息
            # 获取购物车中商品的数量
            try:
                count = cnn.hget(car_key, sku_id)
                count = int(count)
            except:
                # 回滚事务
                transaction.savepoint_rollback(save_point)
                return JsonResponse({"status": 10, "errmsg": "购物车中商品数量不存在"})

            # count = 9999
            # 判断库存是否足够
            if goods_sku.stock < count:
                # 回滚事务
                transaction.savepoint_rollback(save_point)
                return JsonResponse({"status": 7, "errmsg": "商品库存不足!"})

            # time.sleep(10)
            try:
                order_goods = OrderGoods.objects.create(order=orderinfo,
                                                        goods_sku=goods_sku,
                                                        price=goods_sku.price,
                                                        count=count)
            except:
                # 回滚事务
                transaction.savepoint_rollback(save_point)
                return JsonResponse({"status": 8, "errmsg": "创建订单商品失败!"})

            # 对应商品的库存 减少 销量增加
            goods_sku.stock -= count
            # GoodsSKU.objects.filter(pk=goods_sku.pk,stock=goods_sku.stock)
            goods_sku.sale_num += count
            goods_sku.save()

            # 商品总金额计算
            order_goods_money += goods_sku.price * count

        try:
            # 完善订单基本信息
            # 获取 订单总金额和商品总金额
            order_money = order_goods_money + trans.money
            orderinfo.order_money = order_money
            orderinfo.order_goods_money = order_goods_money
            orderinfo.save()
        except:
            # 回滚事务
            transaction.savepoint_rollback(save_point)
            return JsonResponse({"status": 9, "errmsg": "更新订单失败"})

        # 清空购物车 只清空对应的商品
        cnn.hdel(car_key, *sku_ids)
        # 整个订单创建成功, 提交事务
        transaction.savepoint_commit(save_point)

        return JsonResponse({"status": 0, "errmsg": "下单成功", "order_sn": order_sn})


# order
class OrderView(View):
    """
        显示订单页面
    """

    def get(self, request):  # 显示订单
        # 判断是否登录
        user_id = request.session.get("ID")
        if not user_id:
            return redirect(reverse("sp_user:login"))

        # 接收参数
        order_sn = request.GET.get("order_sn")

        # 查询订单信息 基本信息和订单商品信息
        try:
            orderinfo = OrderInfo.objects.get(user_id=user_id,
                                              order_status=0,
                                              is_delete=False,
                                              order_sn=order_sn,
                                              )
        except OrderInfo.DoesNotExist:
            # 如果订单不存在就跳转到个人中心 (显示订单列表)
            return redirect(reverse("sp_user:center"))

        # 获取订单商品信息
        order_goods = orderinfo.ordergoods_set.all()

        context = {
            "orderinfo": orderinfo,
            "order_goods": order_goods,
        }

        return render(request, 'sp_order/order.html', context)

    def post(self, request):  # 提交支付 ajax


        app_private_key_string = open(os.path.join(settings.BASE_DIR,"apps/sp_order/app_private_key.pem")).read()
        alipay_public_key_string = open(os.path.join(settings.BASE_DIR,"apps/sp_order/alipay_public_key.pem")).read()

        alipay = AliPay(
            appid="	2016092000558689",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=app_private_key_string,
            alipay_public_key_string=alipay_public_key_string,  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True  # 默认False 调试的时候使用的沙箱 正式环境是正式地址
        )

        # 电脑网站支付，需要跳转到https://openapi.alipay.com/gateway.do? + order_string
        order_string = alipay.api_alipay_trade_page_pay(
            out_trade_no="order_sn",

SpMarket/templates/sp_order/order.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <h5 class="order-tit">收货人信息</h5>
    <div class="order-name">
        <p class="order-tele">{{ orderinfo.receiver }}&nbsp;&nbsp;&nbsp;{{ orderinfo.receiver_phone }}</p>
        <p class="order-add">{{ orderinfo.address }}</p>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <h5 class="order-tit">确认订单信息</h5>
    <ul class="shopcart-list" style="padding-bottom: 0; margin-top: 0;">
        {% for goods in order_goods %}
        <li>
            <img src="{{ MEDIA_URL }}{{ goods.goods_sku.logo }}" class="shop-pic"/>
            <div class="order-mid">
                <div class="tit">{{ goods.goods_sku.goods_spu.spu_name }}{{ goods.goods_sku.sku_name }}</div>
                <div class="order-price">￥{{ goods.price }} <i>X{{ goods.count }}</i></div>
            </div>
        </li>
        {% endfor %}

    </ul>
    <ul class="order-infor">
        <li class="order-infor-first">
            <span>商品总计：</span>
            <i>￥{{ orderinfo.order_goods_money }}</i>
        </li>
        <li class="order-infor-first">
            <span>运输方式：{{ orderinfo.transport.name }}</span>
            <i>运费:{{ orderinfo.transport_price }}</i>
        </li>
    </ul>
    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" class="bz-infor"></textarea>
    <ul class="pay-style">
        <li>
            <img src="{% static 'images/zhi.png' %}" width="50">
            <span>
		   	 		<p>支付宝</p>
		   	 		<p class="descript">推荐有支付宝账号的用户使用</p>
		   	 	</span>
            <label class="am-radio-inline">
                <input type="radio" checked="checked" name="radio10" value="1" data-am-ucheck=""
                       class="am-ucheck-radio"><span class="am-ucheck-icons"><i class="am-icon-unchecked"></i><i
                    class="am-icon-checked"></i></span>
            </label>
        </li>
    </ul>
    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥{{ orderinfo.order_money }}</span>
        </div>
        <a href="pay.html" class="js-btn">确认支付</a>
    </div>
{% endblock %}


{% block footer %}
    <!--底部-->
    {% include 'public/footer.html' %}
{% endblock %}

SpMarket/templates/sp_order/tureorder.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}

    <form action="" method="post" id="order_form">
    {% csrf_token %}

    {% if address %}
        <div class="order-name">
            <input type="hidden" name="addr_id" value="{{ address.pk }}">
	    	<a href="{% url 'sp_user:address' %}">
	    		<p class="order-tele">{{ address.username }}&nbsp;&nbsp;&nbsp;{{ address.phone }}</p>
	    		<p class="order-add">{{ address.hcity }}&nbsp;{{ address.hproper }}&nbsp;{{ address.harea }}&nbsp;{{ address.brief }}</p>
	    	</a>
	    	<i class="am-icon-angle-right"></i>
	    </div>
        {% else %}
        <div class="add-address">
            <a href="{% url 'sp_user:address_add' %}">+新建收货地址</a>
            <i class="am-icon-angle-right"></i>
        </div>
    {% endif %}


    <div style="background: #eee; height: 10px;"></div>
    <ul class="shopcart-list" style="padding-bottom: 0;">
        {% for goods in goodsList %}
        <li>
            <input type="hidden" name="sku_ids" value="{{ goods.pk }}">
            <img src="{{ MEDIA_URL }}{{ goods.logo }}" class="shop-pic"/>
            <div class="order-mid">
                <div class="tit">{{ goods.goods_spu.spu_name }}{{ goods.sku_name }}</div>
                <div class="order-price">￥{{ goods.price }} <i>X{{ goods.count }}</i></div>
            </div>
        </li>
        {% endfor %}
    </ul>
    <ul class="order-infor">
        <li class="order-infor-first">
            <span>商品总计：</span>
            <i>￥<span id="goods_total_price">{{ goods_total_price }}</span></i>
        </li>
        <li class="order-infor-first">
            <span>运输方式：</span>
            <i>
                <select name="transport">
                    {% for transport in transports %}
                    <option value="{{ transport.pk }}" price="{{ transport.money }}">{{ transport.name }}-{{ transport.money }}</option>
                    {% endfor %}
                </select>
            </i>
        </li>
    </ul>
    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" name="description" class="bz-infor"></textarea>
    </form>

    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥<i id="total_price">{{ total_price }}</i></span>
        </div>
        <a href="javascript:;" class="js-btn">提交订单</a>
    </div>
{% endblock %}



{% block footer %}
    <!--底部-->
    {% include 'public/footer.html' %}
{% endblock %}

{% block footer_js %}
    <script>
        $(function () {
            //绑定运输方式改变事件
            $("select[name='transport']").on("change",function () {
                //重新计算总价 == 商品总价 + 运费
                var goods_total_price = $("#goods_total_price").text();
                var transport_price = $(this).find(":selected").attr("price");
                var total_price = parseFloat(goods_total_price) + parseFloat(transport_price);
                $("#total_price").text(total_price.toFixed(2));
            });

            //提交订单
            $(".js-btn").on("click",function () {
                {#$("#order_form").submit();#}
                if(
                    $("input[name='addr_id']").val()>0
                    && $("select[name='transport']").val()>0
                    && $("input[name='sku_ids']").length > 0
                ){
                    //准备数据
                    var data = $("#order_form").serialize();
                    //发送请求
                    $.post("{% url 'sp_order:确认订单' %}",data,function(data){
                        if(data.status == "0"){
                            location.href = "{% url 'sp_order:显示订单' %}?order_sn=" + data.order_sn;
                        }else {
                            alert(data.errmsg);
                        }
                    });
                }
                else {
                    alert("请选择收货地址和运输方式!");
                }


            })
        })
    </script>
{% endblock %}